### ISSUE TITLE
Bosh-Init error message unhelpful when job template rendering fails

### ISSUE THREAD

**Issue by drich10** [cloudfoundry-incubator/bosh-vcloud-cpi-release#8]
see https://github.com/cloudfoundry/bosh-init/issues/50

**Comment by allomov** [comment]
The problem in https://github.com/cloudfoundry/bosh-init/issues/50 is not on the level of CPI, it's on the level of template renderer. I am convinced that this error is not connected with this repo.

Template renderer takes `cpi.yml.erb` with `spec`, properties from your manifest and tries to merge and to render it. At this moment renderer can't tell using this inputs what properties have wrong format. The discussion of properties validation you can find [here](https://github.com/cloudfoundry/bosh-notes/issues/11).

**Comment by cppforlife** [comment]
Keeping cloudfoundry/bosh-init#50 open. Closing this one.
