### ISSUE TITLE
Multi-Homed VM KO, cpi error in mac addresses

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-vcloud-cpi-release#9]
I expected to vcloud CPI to support multi-homed VM.
https://bosh.io/docs/networks.html#multi-homed
https://bosh.io/docs/networks.html#cpi-limitations

My tests where unsuccessfull. Bosh Director gives 2 IP adress (ok on bosh vms), but the stemcell fails to configure the second NIC.

Having a look at the file /var/vcap/job/settings.json, I see that the 2 nics are set on the same MAC (whereas i have 2 distincts generated MACs, confirmed in vcloud portal).

For me its a blocker. I would be glad if you had any workaround.

Moved from: https://github.com/cloudfoundry-attic/bosh_vcloud_cpi/issues/16

cc @poblin-orange

**Comment by poblin-orange** [comment]
Just did a test with fresher bosh release (211) and stemcell 3137. No more DNS issue, and no Mac problem either.
Guess this issue can be closed
Thanks
Pierre
